env:
    global:
        - PACKAGE="git_comments" # Package name
        - SUBLIME_TEXT_VERSION="3"
        # use UNITTESTING_TAG to specific tag of UnitTesting
        # - UNITTESTING_TAG="master"

# mutliple os matrix
# https://docs.travis-ci.com/user/multi-os/#Python-example-(unsupported-languages)
matrix:
    include:
        - os: linux
          language: python
          python: 3.6

before_install:
    - curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/travis.sh
    # enable gui, see https://docs.travis-ci.com/user/gui-and-headless-browsers
    - if [ "$TRAVIS_OS_NAME" == "linux"  ]; then
            export DISPLAY=:99.0;
            sh -e /etc/init.d/xvfb start;
      fi
    - pip install -U pip
    - export PYTHONPATH=$PYTHONPATH:$(pwd)
    - python3 setup.py install

install:
    # bootstrap the testing environment
    - sh travis.sh bootstrap
    - pip3 install -r requirements.txt
    - pip3 install nose
    # install Package Control and package denepdencies
    # - sh travis.sh install_package_control

script:
    # run tests with test coverage report
    - sh travis.sh run_tests
    - cd utils
    - nosetests
    # testing syntax_test files
    # - sh travis.sh run_syntax_tests

after_success:
    # remove the following if `coveralls` is not needed
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
            brew update;
            brew install python || brew upgrade python;
      fi
    - pip3 install python-coveralls;
    - pip3 install codecov;
    - coveralls
    - codecov

notifications:
    email: false
